<script setup lang="ts">
import CardServicesComponent from '@/components/CardServicesComponent.vue'
import ServicesPageLayoutComponent from '@/components/ServicesPageLayoutComponent.vue'

const services = [
  { id: 1, imagem: '/images/services/frx.avif', nome: 'Fluorescência de Raios-X (FRX)', machine: 'ARL QUANT\'X EDXRF da Thermo Scientific', descricao: 'É uma ferramenta analítica versátil e econômica, projetada para quantificar elementos principais, secundários e traços em uma ampla variedade de amostras, incluindo sólidos em massa, grânulos, pós soltos ou compactados, pastilhas fundidas, filmes finos, pastas e líquidos. Com capacidade para analisar elementos desde o flúor F) até o amerício Am, o instrumento oferece desempenho superior tanto para elementos leves quanto pesados, garantindo rapidez e flexibilidade em um formato compacto de bancada. Além disso, o ARL QUANT\'X minimiza a necessidade de preparação de amostras, tornando-o ideal para laboratórios centrais e contratados que buscam eficiência e precisão em suas análises elementares.' },
  { id: 2, imagem: '/images/services/drx.avif', nome: 'Difração de Raios-X (DRX)', machine: 'Difratômetro de Raios X de Bancada Aeris– Malvern Panalytical', descricao: 'O Aeris é um difratômetro de raios X de bancada, projetado para oferecer análises rápidas, precisas e confiáveis em um formato compacto. Ideal para identificação de fases cristalinas e análise qualitativa, atende diversas aplicações nos setores de mineração, cimento, cerâmica e pesquisa. Com desempenho comparável a equipamentos de grande porte, possui interface intuitiva e recursos automatizados otimizam o fluxo de trabalho no laboratório. O Aeris analisa uma variedade de amostras, incluindo pós, sólidos compactos e pastilhas. É certificado como equipamento de proteção total, garantindo segurança em sua operação. É uma solução versátil, moderna e eficiente para análises por difração de raios-x.' },
  { id: 3, imagem: '/images/services/icp.webp', nome: 'Espectrometria de Emissão Óptica com Plasma Acoplado Indutivamente (ICP-OES)', machine: 'Emissão Óptica com Plasma da Agilent 5800', descricao: 'O ICPOES Agilent 5800 é um espectrômetro multielementar de alta performance, confiável e automatizado, ideal para análises em geologia, mineração, meio ambiente e indústria. Opera com plasma de argônio a temperaturas superiores a 8.000 °C, permitindo atomização eficiente dos elementos. Possui ampla faixa espectral, analisando desde elementos leves como lítio até pesados como urânio. Utiliza digestão ácida para matrizes simples e fusão alcalina para materiais refratários. Aceita amostras de rochas, solos, águas, rejeitos e resíduos. Oferece resultados rápidos, precisos e com correção automática de interferências. Ideal para determinação de elementos maiores, menores, traços e terras raras. Pode ser customizado conforme os elementos de interesse.' },
  { id: 4, imagem: '/images/services/absocao.webp', nome: 'Absorção Atômica (AAS)', machine: 'Espectrômetro de Absorção Atômica SavantAA – GBC', descricao: 'O SavantAA é um espectrômetro de absorção atômica da GBC, projetado para realizar análises químicas precisas e confiáveis na determinação de elementos metálicos em diferentes tipos de amostras. Amplamente utilizado nos setores de mineração, meio ambiente, metalurgia e pesquisa, o equipamento oferece alta sensibilidade e excelente desempenho analítico. Com operação automatizada e interface intuitiva, o SavantAA otimiza a rotina laboratorial, proporcionando rapidez nas análises e maior controle de qualidade dos resultados. O equipamento permite a determinação de diversos elementos em soluções líquidas, utilizando técnicas de chama e forno de grafite, conforme a necessidade analítica. Seu sistema robusto e de fácil operação garante estabilidade, segurança e confiabilidade nos processos, tornando o SavantAA uma solução versátil, moderna e eficiente para análises por absorção atômica.' },
  { id: 5, imagem: '/images/services/granulometro-laser.webp', nome: 'Granulomêtro a Laser', machine: 'Mastersizer 3000', descricao: 'O Mastersizer 3000+ Pro é um analisador de tamanho e distribuição de partículas que utiliza a técnica de difração a laser para fornecer análises rápidas, precisas e confiáveis. Ideal para caracterização granulométrica de materiais, permite determinar o tamanho das partículas a partir da intensidade da luz espalhada quando um feixe de laser interage com as partículas dispersas da amostra. Os dados obtidos são processados para calcular a distribuição do tamanho das partículas com base no padrão de espalhamento gerado. Com tecnologia avançada e resultados precisos e robustos, o Mastersizer 3000+ Pro atende diversas aplicações em processos industriais e laboratórios de pesquisa. É uma solução moderna, eficiente e confiável para análises de tamanho e distribuição de partículas.' },
  { id: 6, imagem: '/images/services/digestao-micro-ondas.avif', nome: 'Digestão por Micro-ondas', machine: 'Multiwave 5001', descricao: 'O Multiwave 5001 é um sistema de digestão e extração por micro-ondas, desenvolvido para oferecer alto desempenho, precisão e confiabilidade em diferentes aplicações laboratoriais. Ideal para processos que vão desde a digestão ácida até a extração de materiais, proporciona elevado rendimento e capacidade de operação em altas temperaturas. Equipado com a tecnologia SmartTemp 2.0, realiza medições de temperatura precisas e estáveis, contribuindo para maior controle dos processos. Com excelente repetibilidade e qualidade consistente, o Multiwave 5001 é uma solução versátil, moderna e eficiente para aplicações laboratoriais que exigem desempenho e confiabilidade.' },
]
</script>

<template>
  <ServicesPageLayoutComponent
    title="Análise Mineral"
    description="Caracterização química e mineralógica com equipamentos de alta precisão para identificar elementos, fases cristalinas e composição de diferentes materiais."
    :service-count="services.length"
  >
    <CardServicesComponent
      v-for="(service, index) in services"
      :key="service.id"
      :index-service="String(index + 1).padStart(2, '0')"
      :name-service="service.nome"
      :machine="service.machine"
      :description-service="service.descricao"
      :image-service="service.imagem"
    />
  </ServicesPageLayoutComponent>
</template>
